FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-devel

WORKDIR /workspace

RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install transformers==2.5.0

WORKDIR /workspace
RUN git clone --branch dev https://github.com/baizh1994/PipeSwitch.git

ENV PYTHONPATH=/workspace/PipeSwitch

WORKDIR /workspace/PipeSwitch
RUN python scripts/environment/container_dowanload_models.py

WORKDIR /workspace
RUN rm -rf PipeSwitch

WORKDIR /workspace