FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-devel

WORKDIR /workspace

RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install transformers==2.5.0

ENV PYTHONPATH=/workspace/PipeSwitch

WORKDIR /workspace